export enum Permission {
  CREATE_EXPENSE = 'CREATE_EXPENSE',
  READ_EXPENSE = 'READ_EXPENSE',
  UPDATE_EXPENSE = 'UPDATE_EXPENSE',
  DELETE_EXPENSE = 'DELETE_EXPENSE',
  APPROVE_EXPENSE = 'APPROVE_EXPENSE',
}
